### ISSUE TITLE
Test interface

### ISSUE THREAD

**Issue by Briefmark** [Sharefunders/SF-bugs#114]
Is there a limit to amount of bids?
Can the interface tackle large amounts of bids?
How to sort?

**Comment by jycr753** [comment]
As is right now, no. there is not limit that a person can make bids.. so it can make any amount of bids for any company listed...

yes it can, since each bid is save as part of an user data

there is not sort method right now, but there are many ways we can solve this. But that is why have the different tables in GUI to separate that data.  as it is right now is order by ASC order..
